apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nqc5aahh8-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nqc5aahh8-java-springboot-gitops